feat: recover plugins meta files
skymavis/waypoint-unity pull request #21
Opened 2024-11-07 09:16 UTC by tiennguyen-sm

2024-11-07 09:48 UTC, long-duc-nguyen-skymavis requested changes

2024-11-07 09:48 UTC, long-duc-nguyen-skymavis commented on Plugins/iOS/waypoint.framework.meta
[MUST] Make sure it is the same as before: https://github.com/skymavis/waypoint-unity/pull/18/files#diff-35911141e3fd06e8506e2d016246e962c25982998718ae53b969f8fb72362109

2024-11-07 09:48 UTC, long-duc-nguyen-skymavis commented on Plugins/Android/waypoint.aar.meta
[MUST] Make sure it is the same as before: https://github.com/skymavis/waypoint-unity/pull/18/files#diff-e2d951b4cf83b4fff9c6aee9d8fee5210aca45b836facc40fae6eb0e742dfd93

2024-11-07 10:54 UTC, tiennguyen-sm commented on Plugins/iOS/waypoint.framework.meta
Done

2024-11-07 10:54 UTC, tiennguyen-sm commented on Plugins/Android/waypoint.aar.meta
Done

2024-11-08 03:37 UTC, long-duc-nguyen-skymavis approved these changes

2024-11-08 03:40 UTC, merged